<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Languages;
use Illuminate\Support\Facades\DB;
class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       $landg=[
        //`id`, `language_code`, `language_name`, `code`
        ['id'=>'1','language_code'=>'af','language_name'=>'afrikaans','code'=>'afrikaans'],
        ['id'=>'2','language_code'=>'ak','language_name'=>'akan','code'=>'akan'],
        ['id'=>'3','language_code'=>'sq','language_name'=>'albanian','code'=>'shqip'],
        ['id'=>'4','language_code'=>'am','language_name'=>'amharic','code'=>'አማርኛ'],
        ['id'=>'5','language_code'=>'ar','language_name'=>'arabic','code'=>'العربية'],
        ['id'=>'6','language_code'=>'hy','language_name'=>'armenian','code'=>'հայերեն'],
        ['id'=>'7','language_code'=>'as','language_name'=>'assamese','code'=>'অসমীয়া'],
        ['id'=>'8','language_code'=>'az','language_name'=>'azerbaijani','code'=>'azərbaycan'],
        ['id'=>'9','language_code'=>'bm','language_name'=>'bambara','code'=>'bamanakan'],
        ['id'=>'10','language_code'=>'bn','language_name'=>'bangla','code'=>'বাংলা'],
        ['id'=>'11','language_code'=>'eu','language_name'=>'basque','code'=>'euskara'],
        ['id'=>'12','language_code'=>'be','language_name'=>'belarusian','code'=>'беларуская'],
        ['id'=>'13','language_code'=>'bs','language_name'=>'bosnian','code'=>'bosanski'],
        ['id'=>'14','language_code'=>'br','language_name'=>'breton','code'=>'brezhoneg'],
        ['id'=>'15','language_code'=>'bg','language_name'=>'bulgarian','code'=>'български'],
        ['id'=>'16','language_code'=>'my','language_name'=>'burmese','code'=>'မြန်မာ'],
        ['id'=>'17','language_code'=>'ca','language_name'=>'catalan','code'=>'català'],
        ['id'=>'18','language_code'=>'ce','language_name'=>'chechen','code'=>'нохчийн'],
        ['id'=>'19','language_code'=>'zh','language_name'=>'chinese','code'=>'中文'],
        ['id'=>'20','language_code'=>'kw','language_name'=>'cornish','code'=>'kernewek'],
        ['id'=>'21','language_code'=>'hr','language_name'=>'croatian','code'=>'hrvatski'],
        ['id'=>'22','language_code'=>'cs','language_name'=>'czech','code'=>'čeština'],
        ['id'=>'23','language_code'=>'da','language_name'=>'danish','code'=>'dansk'],
        ['id'=>'24','language_code'=>'nl','language_name'=>'dutch','code'=>'nederlands'],
        ['id'=>'25','language_code'=>'dz','language_name'=>'dzongkha','code'=>'རྫོང་ཁ'],
        ['id'=>'26','language_code'=>'en','language_name'=>'english','code'=>'english'],
        ['id'=>'27','language_code'=>'eo','language_name'=>'esperanto','code'=>'esperanto'],
        ['id'=>'28','language_code'=>'et','language_name'=>'estonian','code'=>'eesti'],
        ['id'=>'29','language_code'=>'ee','language_name'=>'ewe','code'=>'eʋegbe'],
        ['id'=>'30','language_code'=>'fo','language_name'=>'faroese','code'=>'føroyskt'],
        ['id'=>'31','language_code'=>'fi','language_name'=>'finnish','code'=>'suomi'],
        ['id'=>'32','language_code'=>'fr','language_name'=>'french','code'=>'français'],
        ['id'=>'33','language_code'=>'ff','language_name'=>'fulah','code'=>'pulaar'],
        ['id'=>'34','language_code'=>'gl','language_name'=>'galician','code'=>'galego'],
        ['id'=>'35','language_code'=>'lg','language_name'=>'ganda','code'=>'luganda'],
        ['id'=>'36','language_code'=>'ka','language_name'=>'georgian','code'=>'ქართული'],
        ['id'=>'37','language_code'=>'de','language_name'=>'german','code'=>'deutsch'],
        ['id'=>'38','language_code'=>'el','language_name'=>'greek','code'=>'ελληνικά'],
        ['id'=>'39','language_code'=>'gu','language_name'=>'gujarati','code'=>'ગુજરાતી'],
        ['id'=>'40','language_code'=>'ha','language_name'=>'hausa','code'=>'hausa'],
        ['id'=>'41','language_code'=>'he','language_name'=>'hebrew','code'=>'עברית'],
        ['id'=>'42','language_code'=>'hi','language_name'=>'hindi','code'=>'हिन्दी'],
        ['id'=>'43','language_code'=>'hu','language_name'=>'hungarian','code'=>'magyar'],
        ['id'=>'44','language_code'=>'is','language_name'=>'icelandic','code'=>'íslenska'],
        ['id'=>'45','language_code'=>'ig','language_name'=>'igbo','code'=>'igbo'],
        ['id'=>'46','language_code'=>'id','language_name'=>'indonesian','code'=>'indonesia'],
        ['id'=>'47','language_code'=>'ia','language_name'=>'interlingua','code'=>'interlingua'],
        ['id'=>'48','language_code'=>'ga','language_name'=>'irish','code'=>'gaeilge'],
        ['id'=>'49','language_code'=>'it','language_name'=>'italian','code'=>'italiano'],
        ['id'=>'50','language_code'=>'ja','language_name'=>'japanese','code'=>'日本語'],
        ['id'=>'51','language_code'=>'jv','language_name'=>'javanese','code'=>'jawa'],
        ['id'=>'52','language_code'=>'kl','language_name'=>'kalaallisut','code'=>'kalaallisut'],
        ['id'=>'53','language_code'=>'kn','language_name'=>'kannada','code'=>'ಕನ್ನಡ'],
        ['id'=>'54','language_code'=>'ks','language_name'=>'kashmiri','code'=>'کٲشُر'],
        ['id'=>'55','language_code'=>'kk','language_name'=>'kazakh','code'=>'қазақ тілі'],
        ['id'=>'56','language_code'=>'km','language_name'=>'khmer','code'=>'ខ្មែរ'],
        ['id'=>'57','language_code'=>'ki','language_name'=>'kikuyu','code'=>'gikuyu'],
        ['id'=>'58','language_code'=>'rw','language_name'=>'kinyarwanda','code'=>'kinyarwanda'],
        ['id'=>'59','language_code'=>'ko','language_name'=>'korean','code'=>'한국어'],
        ['id'=>'60','language_code'=>'ku','language_name'=>'kurdish','code'=>'kurdî'],
        ['id'=>'61','language_code'=>'ky','language_name'=>'kyrgyz','code'=>'кыргызча'],
        ['id'=>'62','language_code'=>'lo','language_name'=>'lao','code'=>'ລາວ'],
        ['id'=>'63','language_code'=>'lv','language_name'=>'latvian','code'=>'latviešu'],
        ['id'=>'64','language_code'=>'ln','language_name'=>'lingala','code'=>'lingála'],
        ['id'=>'65','language_code'=>'lt','language_name'=>'lithuanian','code'=>'lietuvių'],
        ['id'=>'66','language_code'=>'lu','language_name'=>'luba-katanga','code'=>'tshiluba'],
        ['id'=>'67','language_code'=>'lb','language_name'=>'luxembourgish','code'=>'lëtzebuergesch'],
        ['id'=>'68','language_code'=>'mk','language_name'=>'macedonian','code'=>'македонски'],
        ['id'=>'69','language_code'=>'mg','language_name'=>'malagasy','code'=>'malagasy'],
        ['id'=>'70','language_code'=>'ms','language_name'=>'malay','code'=>'melayu'],
        ['id'=>'71','language_code'=>'ml','language_name'=>'malayalam','code'=>'മലയാളം'],
        ['id'=>'72','language_code'=>'mt','language_name'=>'maltese','code'=>'malti'],
        ['id'=>'73','language_code'=>'gv','language_name'=>'manx','code'=>'gaelg'],
        ['id'=>'74','language_code'=>'mi','language_name'=>'maori','code'=>'te reo māori'],
        ['id'=>'75','language_code'=>'mr','language_name'=>'marathi','code'=>'मराठी'],
        ['id'=>'76','language_code'=>'mn','language_name'=>'mongolian','code'=>'монгол'],
        ['id'=>'77','language_code'=>'ne','language_name'=>'nepali','code'=>'नेपाली'],
        ['id'=>'78','language_code'=>'nd','language_name'=>'north ndebele','code'=>'isindebele'],
        ['id'=>'79','language_code'=>'se','language_name'=>'northern sami','code'=>'davvisámegiella'],
        ['id'=>'80','language_code'=>'no','language_name'=>'norwegian','code'=>'norsk'],
        ['id'=>'81','language_code'=>'nb','language_name'=>'norwegian bokmål','code'=>'norsk bokmål'],
        ['id'=>'82','language_code'=>'nn','language_name'=>'norwegian nynorsk','code'=>'norsk nynorsk'],
        ['id'=>'83','language_code'=>'or','language_name'=>'odia','code'=>'ଓଡ଼ିଆ'],
        ['id'=>'84','language_code'=>'om','language_name'=>'oromo','code'=>'oromoo'],
        ['id'=>'85','language_code'=>'os','language_name'=>'ossetic','code'=>'ирон'],
        ['id'=>'86','language_code'=>'ps','language_name'=>'pashto','code'=>'پښتو'],
        ['id'=>'87','language_code'=>'fa','language_name'=>'persian','code'=>'فارسی'],
        ['id'=>'88','language_code'=>'pl','language_name'=>'polish','code'=>'polski'],
        ['id'=>'89','language_code'=>'pt','language_name'=>'portuguese','code'=>'português'],
        ['id'=>'90','language_code'=>'pa','language_name'=>'punjabi','code'=>'ਪੰਜਾਬੀ'],
        ['id'=>'91','language_code'=>'qu','language_name'=>'quechua','code'=>'runasimi'],
        ['id'=>'92','language_code'=>'ro','language_name'=>'romanian','code'=>'română'],
        ['id'=>'93','language_code'=>'rm','language_name'=>'romansh','code'=>'rumantsch'],
        ['id'=>'94','language_code'=>'rn','language_name'=>'rundi','code'=>'ikirundi'],
        ['id'=>'95','language_code'=>'ru','language_name'=>'russian','code'=>'русский'],
        ['id'=>'96','language_code'=>'sg','language_name'=>'sango','code'=>'sängö'],
        ['id'=>'97','language_code'=>'sa','language_name'=>'sanskrit','code'=>'संस्कृत भाषा'],
        ['id'=>'98','language_code'=>'gd','language_name'=>'scottish gaelic','code'=>'gàidhlig'],
        ['id'=>'99','language_code'=>'sr','language_name'=>'serbian','code'=>'српски'],
        ['id'=>'100','language_code'=>'sh','language_name'=>'serbo-croatian','code'=>'srpskohrvatski'],
        ['id'=>'101','language_code'=>'sn','language_name'=>'shona','code'=>'chishona'],
        ['id'=>'102','language_code'=>'ii','language_name'=>'sichuan yi','code'=>'ꆈꌠꉙ'],
        ['id'=>'103','language_code'=>'sd','language_name'=>'sindhi','code'=>'سنڌي'],
        ['id'=>'104','language_code'=>'si','language_name'=>'sinhala','code'=>'සිංහල'],
        ['id'=>'105','language_code'=>'sk','language_name'=>'slovak','code'=>'slovenčina'],
        ['id'=>'106','language_code'=>'sl','language_name'=>'slovenian','code'=>'slovenščina'],
        ['id'=>'107','language_code'=>'so','language_name'=>'somali','code'=>'soomaali'],
        ['id'=>'108','language_code'=>'es','language_name'=>'spanish','code'=>'español'],
        ['id'=>'109','language_code'=>'su','language_name'=>'sundanese','code'=>'basa sunda'],
        ['id'=>'110','language_code'=>'sw','language_name'=>'swahili','code'=>'kiswahili'],
        ['id'=>'111','language_code'=>'sv','language_name'=>'swedish','code'=>'svenska'],
        ['id'=>'112','language_code'=>'tl','language_name'=>'tagalog','code'=>'tagalog'],
        ['id'=>'113','language_code'=>'tg','language_name'=>'tajik','code'=>'тоҷикӣ'],
        ['id'=>'114','language_code'=>'ta','language_name'=>'tamil','code'=>'தமிழ்'],
        ['id'=>'115','language_code'=>'tt','language_name'=>'tatar','code'=>'татар'],
        ['id'=>'116','language_code'=>'te','language_name'=>'telugu','code'=>'తెలుగు'],
        ['id'=>'117','language_code'=>'th','language_name'=>'thai','code'=>'ไทย'],
        ['id'=>'118','language_code'=>'bo','language_name'=>'tibetan','code'=>'བོད་སྐད་'],
        ['id'=>'119','language_code'=>'ti','language_name'=>'tigrinya','code'=>'ትግር'],
        ['id'=>'120','language_code'=>'to','language_name'=>'tongan','code'=>'lea fakatonga'],
        ['id'=>'121','language_code'=>'tr','language_name'=>'turkish','code'=>'türkçe'],
        ['id'=>'122','language_code'=>'tk','language_name'=>'turkmen','code'=>'türkmen dili'],
        ['id'=>'123','language_code'=>'uk','language_name'=>'ukrainian','code'=>'українська'],
        ['id'=>'124','language_code'=>'ur','language_name'=>'urdu','code'=>'اردو'],
        ['id'=>'125','language_code'=>'ug','language_name'=>'uyghur','code'=>'ئۇيغۇرچە'],
        ['id'=>'126','language_code'=>'uz','language_name'=>'uzbek','code'=>'o‘zbek'],
        ['id'=>'127','language_code'=>'vi','language_name'=>'vietnamese','code'=>'tiếng việt'],
        ['id'=>'128','language_code'=>'cy','language_name'=>'welsh','code'=>'cymraeg'],
        ['id'=>'129','language_code'=>'fy','language_name'=>'western frisian','code'=>'frysk'],
        ['id'=>'130','language_code'=>'wo','language_name'=>'wolof','code'=>'wolof'],
        ['id'=>'131','language_code'=>'xh','language_name'=>'xhosa','code'=>'isixhosa'],
        ['id'=>'132','language_code'=>'yi','language_name'=>'yiddish','code'=>'ייִדיש'],
        ['id'=>'133','language_code'=>'yo','language_name'=>'yoruba','code'=>'èdè yorùbá'],
        ['id'=>'134','language_code'=>'zu','language_name'=>'zulu','code'=>'isizulu'],
       ];
     if(DB::table('languages')->count()==0){
          DB::table('languages')->insert($landg);
      }
    }
}
