<datalist id="tickmarks">
            <option value="0" label="0%">
            <option value="1" label="1%">
            <option value="2" label="2%">
            <option value="3" label="3%">
            <option value="4" label="4%">
            <option value="5" label="5%">
            <option value="6" label="6%">
            <option value="7" label="7%">
            <option value="8" label="8%">
            <option value="9" label="9%">
            <option value="10" label="10%">
            <option value="11" label="11%">
            <option value="12" label="12%">
            <option value="13" label="13%">
            <option value="14" label="14%">
            <option value="15" label="15%">
            <option value="16" label="16%">
            <option value="17" label="17%">
            <option value="18" label="18%">
            <option value="19" label="19%">
            <option value="20" label="20%">
            <option value="21" label="21%">
            <option value="22" label="22%">
            <option value="23" label="23%">
            <option value="24" label="24%">
            <option value="25" label="25%">
            <option value="26" label="26%">
            <option value="27" label="27%">
            <option value="28" label="28%">
            <option value="29" label="29%">
            <option value="30" label="30%">
            <option value="31" label="31%">
            <option value="32" label="32%">
            <option value="33" label="33%">
            <option value="34" label="34%">
            <option value="35" label="35%">
            <option value="36" label="36%">
            <option value="37" label="37%">
            <option value="38" label="38%">
            <option value="39" label="39%">
            <option value="40" label="40%">
            <option value="41" label="41%">
            <option value="42" label="42%">
            <option value="43" label="43%">
            <option value="44" label="44%">
            <option value="45" label="45%">
            <option value="46" label="46%">
            <option value="47" label="47%">
            <option value="48" label="48%">
            <option value="49" label="49%">                
            <option value="50" label="50%">
            <option value="51" label="51%">
            <option value="52" label="52%">
            <option value="53" label="53%">
            <option value="54" label="54%">
            <option value="55" label="55%">
            <option value="56" label="56%">
            <option value="57" label="57%">
            <option value="58" label="58%">
            <option value="59" label="59%">
            <option value="60" label="60%">
            <option value="61" label="61%">
            <option value="62" label="62%">
            <option value="63" label="63%">
            <option value="64" label="64%">
            <option value="65" label="65%">
            <option value="66" label="66%">
            <option value="67" label="67%">
            <option value="68" label="68%">
            <option value="69" label="69%">
            <option value="70" label="70%">
            <option value="71" label="71%">
            <option value="72" label="72%">
            <option value="73" label="73%">
            <option value="74" label="74%">
            <option value="75" label="75%">
            <option value="76" label="76%">
            <option value="77" label="77%">
            <option value="78" label="78%">
            <option value="79" label="79%">
            <option value="80" label="80%">
            <option value="81" label="81%">
            <option value="82" label="82%">
            <option value="83" label="83%">
            <option value="84" label="84%">
            <option value="85" label="85%">
            <option value="86" label="86%">
            <option value="87" label="87%">
            <option value="88" label="88%">
            <option value="89" label="89%">
            <option value="90" label="90%">
            <option value="91" label="91%">
            <option value="92" label="92%">
            <option value="93" label="93%">
            <option value="94" label="94%">
            <option value="95" label="95%">
            <option value="96" label="96%">
            <option value="97" label="97%">
            <option value="98" label="98%">
            <option value="99" label="99%">
            <option value="100" label="100%">
            </datalist>